AKISMET_API: "YOUR ASKIMET API KEY"
AWS_ACCESS_KEY_ID: "YOUR AWS KEY"
AWS_SECRET_ACCESS_KEY: "YOUR AWS SECRET"
AWS_BUCKET: "YOUR AWS BUCKET"
SECRET_TOKEN: "YOUR SECRET TOKEN"
STRIPE_CLIENT_ID: "YOUR STRIPE CLIENT ID"
STRIPE_PUBLISHABLE: "YOUR STRIPE PUBLISHABLE KEY"